# Generated by Django 3.2.25 on 2024-03-11 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='collectionpic',
            new_name='collectionloc',
        ),
        migrations.AddField(
            model_name='donation',
            name='documentation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('Footware Donation', 'Footwear Donation'), ('Furniture Donation', 'Furniture Donation'), ('other', 'other'), ('Books Donation', 'Books Donation'), ('Vessel Donation', 'Vessel Donation'), ('Food Donation', 'Food Donation'), ('Cloth Donation', 'Cloth Donation')], max_length=100, null=True),
        ),
    ]
