# Generated by Django 3.2.25 on 2024-03-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240311_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('Cloth Donation', 'Cloth Donation'), ('Furniture Donation', 'Furniture Donation'), ('Books Donation', 'Books Donation'), ('Food Donation', 'Food Donation'), ('Vessel Donation', 'Vessel Donation'), ('other', 'other'), ('Footware Donation', 'Footwear Donation')], max_length=100, null=True),
        ),
    ]
